<?php
/** 
 * @file
 * All functionality of resetpassword module.
 */

/**
 * Implements hook_menu().
 */
function resetpassword_menu() {
  $menu['admin/resetpassword'] = array(
    'title' => 'Ajax ',
    'page callback' => 'resetpassword_manage_item_page',
    'access callback' => TRUE,
  );
  return $menu;
}
/**
 * Mylogin menu calling the form.
 */
function resetpassword_manage_item_page() {
  return drupal_get_form('ajax_example_autotextfields');
}
 
function ajax_example_autotextfields($form, &$form_state) {
 
  
  $form['country'] = array(
    '#title' => t('Country'),
    '#type' => 'select',
    '#options' => get_country(),
    '#ajax' => array(
      'event'=>'change',
      'callback' =>'sandbox_ajax_dropdown_city',
      'wrapper' => 'city-wrapper',
    ),
  );
 
 $form['wrapper'] = array(
    '#prefix' => '<div id="city-wrapper">',
    '#suffix' => '</div>',
  );
 
  $options = array('- Select city -');
  if (isset($form_state['values']['country'])) {
    // Pre-populate options for city dropdown list if province id is set
    $options = get_city($form_state['values']['country']);
  }else
  {
    $options = array('0' => 'No city found');
  }
 
  $form['wrapper']['city'] = array(
    '#title' => t('City'),
    '#type' => 'select',
    '#options' => $options,
  );
   
  return $form;

}

/**
 * Function for handling ajax request
 */
function sandbox_ajax_dropdown_city($form, $form_state) {
  // Return the dropdown list including the wrapper
  return $form['wrapper'];
}

function get_country()
{
  $cn = array('0' => 'Select country');
	$result = db_query('SELECT id,country_name FROM country ORDER BY country_name');
    	foreach ($result as $row) {
		$send[$row->id] = $row->country_name;
	  }
	//  array_unshift($send, "Select country");
	return  $cn + $send;
}

function get_city($province_id) {	
	$c_id =$province_id;
	$sql=  "SELECT id,c_id,city_name FROM city where c_id=$c_id";	 
	$results = db_query($sql);
	$options_city =array();
	foreach ($results as $rows) {
		$options_city[$rows->id] = $rows->city_name;
	  }	 
	  
	return $options_city;
}
 